{% set name = "georaster" %}
{% set version = "1.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b938a1b5bfed8e24fca717470d547e82b438b5f8d717ee6806ad2a84965721f

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - gdal
    - pyproj

test:
  imports:
    - georaster

about:
  home: https://github.com/GeoUtils/georaster
  license: GNU GPL v.3
  summary: 'easy processing and analysis of geographic and projected rasters'
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  doc_url: http://georaster.readthedocs.io
  dev_url: https://github.com/GeoUtils/georaster

extra:
  recipe-maintainers:
    - atedstone
